In [1]:
import numpy as np
import pandas as pd

In [70]:
import pandas as pd
df1 = pd.DataFrame({'A': ['2', '2', '2', '2'],
                    'B': ['2', '3', '3', '4'],
                    'C': ['5', '10', '15', '20'],
                    'D': ['1', '2', '3', '4']},
                    index=[0, 1, 2, 3])  
df2 = pd.DataFrame({'A': ['3', '3', '3', '3'],
                    'B': ['11', '26', '16', '46'],
                    'C': ['55', '36', '62', '83'],
                    'D': ['22', '37', '13', '45']},
                    index=[0, 1, 2, 3])
df3 = pd.DataFrame({'A': ['3', '3', np.NAN,'3'],
                    'B': [np.NAN, '26', '16', np.NAN],
                    'C': ['55', '36', np.NAN, '83'],
                    'D': ['好', '好', '坏', '不错']},
                    index=[0, 1, 2, 3])
df1

A  B   C  D
0  2  2   5  1
1  2  3  10  2
2  2  3  15  3
3  2  4  20  4

In [5]:
df2

A   B   C   D
0  3  11  55  22
1  3  26  36  37
2  3  16  62  13
3  3  46  83  45

### StandardScaler

In [18]:
from sklearn.preprocessing import StandardScaler
ss = StandardScaler()
ss.fit_transform(df1)

array([[ 0.        , -1.41421356, -1.34164079, -1.34164079],
       [ 0.        ,  0.        , -0.4472136 , -0.4472136 ],
       [ 0.        ,  0.        ,  0.4472136 ,  0.4472136 ],
       [ 0.        ,  1.41421356,  1.34164079,  1.34164079]])

In [19]:
ss.transform(df2)

array([[  1.        ,  11.3137085 ,   7.60263112,  17.44133022],
       [  1.        ,  32.52691193,   4.2038078 ,  30.85773809],
       [  1.        ,  18.38477631,   8.85482919,   9.39148551],
       [  1.        ,  60.81118318,  12.61142339,  38.01315562]])

In [20]:
ss.fit_transform(df2)

array([[ 0.        , -1.02575529, -0.23798565, -0.58011603],
       [ 0.        ,  0.09325048, -1.36841747,  0.62012404],
       [ 0.        , -0.65275337,  0.17848924, -1.30026008],
       [ 0.        ,  1.58525817,  1.42791388,  1.26025208]])

### MinMaxScaler

In [21]:
from sklearn.preprocessing import MinMaxScaler
ms = MinMaxScaler()
ms.fit_transform(df1)

array([[ 0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.5       ,  0.33333333,  0.33333333],
       [ 0.        ,  0.5       ,  0.66666667,  0.66666667],
       [ 0.        ,  1.        ,  1.        ,  1.        ]])

In [22]:
ms.transform(df2)

array([[  1.        ,   4.5       ,   3.33333333,   7.        ],
       [  1.        ,  12.        ,   2.06666667,  12.        ],
       [  1.        ,   7.        ,   3.8       ,   4.        ],
       [  1.        ,  22.        ,   5.2       ,  14.66666667]])

In [23]:
ms.fit_transform(df2)

array([[ 0.        ,  0.        ,  0.40425532,  0.28125   ],
       [ 0.        ,  0.42857143,  0.        ,  0.75      ],
       [ 0.        ,  0.14285714,  0.55319149,  0.        ],
       [ 0.        ,  1.        ,  1.        ,  1.        ]])

### Normalize

In [9]:
from sklearn.preprocessing import Normalizer # fit是没有实际作用的
NL = Normalizer()
NL.fit_transform(df1)
NL.transform(df2)

array([[ 0.04973135,  0.18234827,  0.91174137,  0.36469655],
       [ 0.05183211,  0.44921158,  0.62198527,  0.63926263],
       [ 0.04586706,  0.2446243 ,  0.94791916,  0.19875724],
       [ 0.02855331,  0.43781735,  0.78997478,  0.42829958]])

In [36]:
NL.fit_transform(df2)

array([[ 0.04973135,  0.18234827,  0.91174137,  0.36469655],
       [ 0.05183211,  0.44921158,  0.62198527,  0.63926263],
       [ 0.04586706,  0.2446243 ,  0.94791916,  0.19875724],
       [ 0.02855331,  0.43781735,  0.78997478,  0.42829958]])

### Binarizer

In [33]:
df1

A  B   C  D
0  2  2   5  1
1  2  3  10  2
2  2  3  15  3
3  2  4  20  4

In [35]:
from sklearn.preprocessing import Binarizer # fit是没有实际作用的
br = Binarizer(2)
br.fit_transform(df1)

array([[ 0.,  0.,  1.,  0.],
       [ 0.,  1.,  1.,  0.],
       [ 0.,  1.,  1.,  1.],
       [ 0.,  1.,  1.,  1.]])

In [34]:
br2 = Binarizer(3)
br2.transform(df)

array([[ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  1.,  1.,  1.]])

In [37]:
br2.transform(df1['B'])

C:\Anaconda3\lib\site-packages\sklearn\utils\validation.py:386: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and willraise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  DeprecationWarning)


array([[ 0.,  0.,  0.,  1.]])

### OneHotEncoder

In [71]:
df3

A    B    C   D
0    3  NaN   55   好
1    3   26   36   好
2  NaN   16  NaN   坏
3    3  NaN   83  不错

In [53]:
from sklearn.preprocessing import OneHotEncoder
oe = OneHotEncoder()

In [55]:
# pandas的便利
pd.get_dummies(df3,columns=["D"])

A   B   C  D_不错  D_坏  D_好
0  3  11  55   0.0  0.0  1.0
1  3  26  36   0.0  0.0  1.0
2  3  16  62   0.0  1.0  0.0
3  3  46  83   1.0  0.0  0.0

### Imputer

In [87]:
df3

A    B    C   D
0    3  NaN   55   好
1    3   26   36   好
2  NaN   16  NaN   坏
3    3  NaN   83  不错

In [79]:
df3.isnull().sum()

A    1
B    2
C    1
D    0
dtype: int64

In [88]:
from sklearn.preprocessing import Imputer
ip = Imputer(missing_values='NaN',strategy='mean',axis=0) 
ip.fit_transform(df3.iloc[:,:3])

array([[  3.,  21.,  55.],
       [  3.,  26.,  36.],
       [  3.,  16.,  58.],
       [  3.,  21.,  83.]])

In [90]:
ip = Imputer(missing_values='NaN',strategy='mean',axis=1)
ip.fit_transform(df3.iloc[:,:3])

array([[  3.,  29.,  55.],
       [  3.,  26.,  36.],
       [ 16.,  16.,  16.],
       [  3.,  43.,  83.]])